type Post {
  id: ID
  uuid: ID
  title: String
  description: String
  cover: String
  tags: [String]
  slug: String
  visits: Int
  removedAt: RemovedAt
  ratings: String
  createdAt: String
  brand: Option!
  model: Option!
  year: Int
  mileage: Mileage
  fuel: Option
  transmission: Option
  paintColor: Option
  interiorColor: Option
  images: [String]
  pricing: Price
  doors: Int
  category: Option
  condition: Option
  features: [Option]
  scores: [Score]
  cylinders: Int
  passengers: Int
  traction: Option
  accessories: [Option]
  includeds: [Option]
  agency: Agency!
  isTheOwner: Boolean
  typeModel: Option
  version: Option
}
input PostInput {
  typeModel: ID
  title: String!
  description: String!
  tags: [String]!
  brand: ID!
  model: ID!
  year: Int!
  mileage: MileageInput!
  fuel: ID!
  transmission: ID!
  paintColor: ID!
  interiorColor: ID!
  images: [PictureInput!]!
  pricing: PriceInput!
  doors: Int!
  category: ID!
  condition: ID!
  cover: String!
  features: [ID!]!
  cylinders: Int!
  passengers: Int!
  traction: ID!
  accessories: [ID!]!
  version: ID!
  includeds: [ID!]!
}

input SearchPostFilter {
  brand: String
  model: String
  typeModel: String
  category: String
  maxYear: Int
  maxPrice: Int
  minYear: Int
  minPrice: Int
  condition: String
  createdAt: String
  province: String
}